name: Java CI with Gradle
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java }}
    strategy:
      matrix:
        java: [ '8', '11', '17' ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: [ 'temurin', 'zulu', 'adopt', 'adopt-openj9', 'liberica', 'microsoft', 'corretto', 'oracle' ]
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        run: ./gradlew build
      - name: Test Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}